(() => {
  'use strict';

  const data = window.DEFINEIX_DATA;
  if (!Array.isArray(data)) return;

  const specs = [
    {word:'plàtan',area:'Alimentació',level:1,extra:'que sovint es ven en grups de diverses peces',ci:[['QUÈ ÉS?','Una fruita allargada amb pell groga quan és madura'],['COM ES MENJA?','que es pela abans de menjar-la']],cm:[['QUÈ ÉS?','Una fruita allargada que creix en grans grups'],['COM ÉS?','que té una pell gruixuda que es retira fàcilment'],['COM ES MENJA?','i es menja habitualment crua']],cs:[['QUÈ ÉS?','Una fruita carnosa de forma allargada'],['COM ÉS?','que presenta una pell exterior que canvia de color en madurar'],['COM ES CONSUMEIX?','i es consumeix normalment després de retirar-ne la pell']]},
    {word:'taronja',area:'Alimentació',level:1,extra:'que pot aparèixer dibuixada en envasos de suc',ci:[['QUÈ ÉS?','Una fruita rodona de color taronja'],['COM ÉS?','que té grills amb suc a l’interior']],cm:[['QUÈ ÉS?','Una fruita cítrica de forma arrodonida'],['COM ÉS?','que té una pell gruixuda i grills sucosos'],['COM ES POT MENJAR?','i es pot menjar sencera o fer-ne suc']],cs:[['QUÈ ÉS?','Una fruita cítrica de forma aproximadament esfèrica'],['QUÈ TÉ?','que conté grills rics en suc protegits per una pell'],['COM ES CONSUMEIX?','i es consumeix fresca o transformada en suc i altres preparacions']]},
    {word:'formatge',area:'Alimentació',level:2,extra:'que pot tenir forats visibles en algunes varietats',ci:[['QUÈ ÉS?','Un aliment que es fa principalment amb llet'],['COM ES MENJA?','que es pot menjar sol o amb altres aliments']],cm:[['QUÈ ÉS?','Un aliment elaborat a partir de llet'],['COM ES FA?','que es produeix transformant i deixant reposar la llet'],['COM POT SER?','i pot tenir textures i sabors molt diferents']],cs:[['QUÈ ÉS?','Un aliment obtingut mitjançant la transformació de la llet'],['COM S’ELABORA?','que es forma separant i tractant una part sòlida de la llet'],['COM POT VARIAR?','i presenta moltes varietats segons l’elaboració i el temps de maduració']]},
    {word:'llet',area:'Alimentació',level:1,extra:'que es pot vendre en ampolles o brics de colors diferents',ci:[['QUÈ ÉS?','Un líquid blanc que es pot beure'],['D’ON POT VENIR?','que pot provenir d’animals com la vaca']],cm:[['QUÈ ÉS?','Un aliment líquid produït pels mamífers'],['COM ÉS?','que habitualment té un color blanquinós'],['COM S’UTILITZA?','i es beu o s’utilitza per preparar molts aliments']],cs:[['QUÈ ÉS?','Un líquid nutritiu produït per les glàndules mamàries dels mamífers'],['QUÈ CONTÉ?','que aporta aigua i diversos nutrients'],['COM S’UTILITZA?','i es consumeix directament o com a ingredient de molts productes alimentaris']]},
    {word:'arròs',area:'Alimentació',level:2,extra:'que pot servir-se en plats de molts colors',ci:[['QUÈ ÉS?','Un aliment format per grans petits'],['COM ES MENJA?','que normalment es cou abans de menjar-lo']],cm:[['QUÈ ÉS?','Un cereal que consumim en forma de grans petits'],['COM ES PREPARA?','que es cuina habitualment amb aigua o brou'],['COM S’UTILITZA?','i forma part de molts plats diferents']],cs:[['QUÈ ÉS?','Un cereal cultivat principalment per obtenir-ne els grans comestibles'],['COM ES PREPARA?','que acostuma a consumir-se després de coure els grans'],['QUIN ÚS TÉ?','i constitueix un aliment bàsic en moltes cuines del món']]},
    {word:'galeta',area:'Alimentació',level:1,extra:'que pot tenir formes d’animals o personatges',ci:[['QUÈ ÉS?','Un aliment petit i sec fet amb una massa'],['COM ES PREPARA?','que es cou al forn']],cm:[['QUÈ ÉS?','Un aliment de mida petita fet amb una massa de farina i altres ingredients'],['COM ES FA?','que es modela i es cou fins que queda sec o cruixent'],['COM ES MENJA?','i es consumeix sovint com a esmorzar o berenar']],cs:[['QUÈ ÉS?','Un producte de fleca petit elaborat a partir d’una massa'],['COM S’ELABORA?','que es forma en porcions i es cou fins a obtenir una textura més o menys seca'],['COM ES CONSUMEIX?','i es menja habitualment com a acompanyament o entre àpats']]},
    {word:'ou',area:'Alimentació',level:1,extra:'que pot estar decorat en algunes celebracions',ci:[['QUÈ ÉS?','Un aliment amb closca que ponen alguns animals'],['QUÈ TÉ A DINS?','que conté clara i rovell']],cm:[['QUÈ ÉS?','Una estructura amb closca que produeixen animals com les aus'],['QUÈ CONTÉ?','que en el cas de l’ou de gallina conté clara i rovell'],['COM S’UTILITZA?','i s’utilitza com a aliment de moltes maneres']],cs:[['QUÈ ÉS?','Una estructura reproductora produïda per diversos grups d’animals'],['COM ESTÀ PROTEGIT?','que en moltes aus està envoltada per una closca'],['QUIN ÚS ALIMENTARI TÉ?','i alguns ous, especialment els de gallina, es consumeixen com a aliment']]},
    {word:'tomàquet',area:'Alimentació',level:2,extra:'que pot tenir una etiqueta enganxada quan es ven',ci:[['QUÈ ÉS?','Un fruit que acostuma a ser vermell quan és madur'],['COM ES MENJA?','que es pot menjar cru o cuinat']],cm:[['QUÈ ÉS?','Un fruit carnós produït per la tomaquera'],['COM ÉS?','que sol tenir molta aigua i llavors a l’interior'],['COM S’UTILITZA?','i es consumeix cru o cuinat en molts plats']],cs:[['QUÈ ÉS?','El fruit comestible de la tomaquera'],['COM ÉS?','que és carnós, ric en aigua i conté nombroses llavors'],['COM S’UTILITZA?','i s’empra fresc o cuinat en una gran varietat de preparacions']]},

    {word:'sofà',area:'Casa',level:1,extra:'que pot tenir coixins decoratius de molts colors',ci:[['QUÈ ÉS?','Un seient gran per a més d’una persona'],['PER A QUÈ SERVEIX?','que serveix per seure i descansar']],cm:[['QUÈ ÉS?','Un moble entapissat preparat perquè hi seguin diverses persones'],['COM ÉS?','que sol tenir respatller i braços'],['PER A QUÈ SERVEIX?','i s’utilitza principalment per seure o descansar']],cs:[['QUÈ ÉS?','Un moble de seient ample i habitualment entapissat'],['COM ESTÀ FORMAT?','que disposa de respatller i espai per a diversos ocupants'],['QUINA FUNCIÓ TÉ?','i està destinat principalment al descans en posició asseguda']]},
    {word:'armari',area:'Casa',level:1,extra:'que pot tenir adhesius enganxats a les portes',ci:[['QUÈ ÉS?','Un moble amb espai a dins per guardar coses'],['QUÈ HI PODEM GUARDAR?','que sovint serveix per guardar roba']],cm:[['QUÈ ÉS?','Un moble tancat amb portes i espai interior'],['COM S’ORGANITZA?','que pot tenir prestatges, calaixos o barres'],['PER A QUÈ SERVEIX?','i s’utilitza per guardar roba o altres objectes']],cs:[['QUÈ ÉS?','Un moble d’emmagatzematge tancat habitualment per portes'],['COM POT ESTAR ORGANITZAT?','que pot incorporar prestatges, calaixos o espais per penjar objectes'],['QUINA FUNCIÓ TÉ?','i permet guardar i ordenar roba o altres pertinences']]},
    {word:'mirall',area:'Casa',level:1,extra:'que pot tenir un marc de fusta de color daurat',ci:[['QUÈ ÉS?','Una superfície on podem veure la nostra imatge'],['COM FUNCIONA?','que reflecteix la llum']],cm:[['QUÈ ÉS?','Una superfície llisa que reflecteix la llum'],['QUÈ HI VEIEM?','que permet veure una imatge reflectida dels objectes que té al davant'],['PER A QUÈ S’UTILITZA?','i s’utilitza sovint per mirar-nos']],cs:[['QUÈ ÉS?','Una superfície preparada per reflectir una gran part de la llum que rep'],['QUÈ PRODUEIX?','que forma una imatge aparent dels objectes situats al davant'],['QUIN ÚS TÉ?','i s’utilitza tant en la vida quotidiana com en diversos aparells òptics']]},
    {word:'dutxa',area:'Casa',level:1,extra:'que pot tenir una cortina amb dibuixos',ci:[['QUÈ ÉS?','Un lloc o aparell d’on cau aigua per rentar-nos'],['PER A QUÈ SERVEIX?','que serveix per netejar el cos']],cm:[['QUÈ ÉS?','Una instal·lació que deixa caure aigua sobre el cos'],['COM S’UTILITZA?','que permet rentar-se estant dret'],['PER A QUÈ SERVEIX?','i s’utilitza principalment per a la higiene personal']],cs:[['QUÈ ÉS?','Una instal·lació sanitària que projecta aigua sobre el cos'],['COM FUNCIONA?','que distribueix l’aigua a través d’un capçal o sistema semblant'],['QUINA FUNCIÓ TÉ?','i permet rentar-se de manera ràpida i habitualment en posició dreta']]},
    {word:'tovallola',area:'Casa',level:1,extra:'que pot portar el nom d’un hotel brodat',ci:[['QUÈ ÉS?','Una peça de roba que absorbeix aigua'],['PER A QUÈ SERVEIX?','que serveix per eixugar-nos']],cm:[['QUÈ ÉS?','Una peça de teixit absorbent'],['COM ÉS?','que està preparada per retenir aigua'],['PER A QUÈ SERVEIX?','i s’utilitza per eixugar el cos o altres superfícies']],cs:[['QUÈ ÉS?','Una peça de teixit fabricada amb material absorbent'],['QUINA PROPIETAT TÉ?','que pot retenir una quantitat considerable d’aigua'],['QUIN ÚS TÉ?','i s’utilitza principalment per assecar el cos després de rentar-se']]},
    {word:'coixí',area:'Casa',level:1,extra:'que pot tenir una funda amb dibuixos',ci:[['QUÈ ÉS?','Un objecte tou que serveix per recolzar una part del cos'],['ON S’UTILITZA?','que sovint es posa al llit o al sofà']],cm:[['QUÈ ÉS?','Un objecte tou i farcit recobert de tela'],['PER A QUÈ SERVEIX?','que permet recolzar el cap o altres parts del cos'],['ON ES TROBA?','i s’utilitza sobretot en llits, sofàs o seients']],cs:[['QUÈ ÉS?','Una peça flexible formada per una funda que conté material tou'],['QUINA FUNCIÓ TÉ?','que proporciona suport i comoditat a una part del cos'],['ON S’UTILITZA?','i s’empra habitualment en llits, sofàs i altres llocs de descans']]},
    {word:'manta',area:'Casa',level:1,extra:'que pot tenir serrells a les vores',ci:[['QUÈ ÉS?','Una peça gran de roba que serveix per tapar-nos'],['PER A QUÈ SERVEIX?','que ajuda a mantenir-nos calents']],cm:[['QUÈ ÉS?','Una peça gran de teixit utilitzada per cobrir el cos'],['COM ÉS?','que acostuma a ser flexible i relativament gruixuda'],['PER A QUÈ SERVEIX?','i ajuda a conservar la calor corporal']],cs:[['QUÈ ÉS?','Una peça tèxtil ampla destinada a cobrir persones o superfícies'],['QUINA PROPIETAT TÉ?','que redueix la pèrdua de calor quan cobreix el cos'],['QUIN ÚS TÉ?','i s’utilitza principalment per proporcionar escalfor i comoditat']]},
    {word:'tassa',area:'Casa',level:1,extra:'que pot portar una fotografia impresa',ci:[['QUÈ ÉS?','Un recipient petit per beure'],['COM ÉS?','que normalment té una nansa']],cm:[['QUÈ ÉS?','Un recipient petit destinat a contenir begudes'],['COM ÉS?','que sol tenir una nansa lateral per agafar-lo'],['COM S’UTILITZA?','i s’utilitza sobretot per beure líquids calents o freds']],cs:[['QUÈ ÉS?','Un recipient individual per a begudes, habitualment amb nansa'],['COM ESTÀ DISSENYAT?','que permet sostenir-lo amb facilitat mentre conté líquid'],['QUIN ÚS TÉ?','i s’utilitza especialment per servir i consumir begudes']]},
    {word:'clau',area:'Casa',level:1,extra:'que pot portar un clauer de colors',ci:[['QUÈ ÉS?','Un objecte petit que serveix per obrir alguns panys'],['COM S’UTILITZA?','que s’introdueix al pany i es gira']],cm:[['QUÈ ÉS?','Un objecte amb una forma preparada per encaixar en un pany'],['COM FUNCIONA?','que permet moure el mecanisme del pany quan és la clau adequada'],['PER A QUÈ SERVEIX?','i s’utilitza per obrir o tancar portes i altres accessos']],cs:[['QUÈ ÉS?','Una peça dissenyada per accionar el mecanisme d’un pany concret'],['COM FUNCIONA?','que encaixa en el sistema intern i permet desbloquejar-lo o bloquejar-lo'],['QUINA FUNCIÓ TÉ?','i controla l’accés a portes, vehicles, armaris o altres elements tancats']]},
    {word:'calaix',area:'Casa',level:1,extra:'que pot tenir un tirador de forma rodona',ci:[['QUÈ ÉS?','Una caixa que entra i surt d’un moble'],['PER A QUÈ SERVEIX?','que serveix per guardar coses']],cm:[['QUÈ ÉS?','Un compartiment en forma de caixa que llisca dins d’un moble'],['COM S’OBRE?','que es desplaça cap enfora per accedir al seu interior'],['PER A QUÈ SERVEIX?','i permet guardar i ordenar objectes']],cs:[['QUÈ ÉS?','Un compartiment mòbil integrat habitualment en un moble'],['COM FUNCIONA?','que llisca sobre guies o suports per entrar i sortir de l’estructura'],['QUINA FUNCIÓ TÉ?','i proporciona un espai accessible per emmagatzemar objectes']]},

    {word:'quadern',area:'Escola',level:1,extra:'que pot tenir la portada decorada amb adhesius',ci:[['QUÈ ÉS?','Un conjunt de fulls units per escriure-hi'],['PER A QUÈ SERVEIX?','que serveix per fer feines o prendre notes']],cm:[['QUÈ ÉS?','Un conjunt de fulls enquadernats en un format manejable'],['QUÈ S’HI FA?','que permet escriure, dibuixar o prendre apunts'],['ON S’UTILITZA?','i s’utilitza molt a l’escola i en altres activitats']],cs:[['QUÈ ÉS?','Una publicació de fulls units i habitualment protegits per una coberta'],['QUINA FUNCIÓ TÉ?','que ofereix un suport ordenat per escriure, dibuixar o registrar informació'],['ON S’UTILITZA?','i és habitual en contextos escolars, personals i professionals']]},
    {word:'goma',area:'Escola',level:1,extra:'que pot tenir forma d’animal',ci:[['QUÈ ÉS?','Un objecte petit que serveix per esborrar llapis'],['COM S’UTILITZA?','que es frega damunt del que volem esborrar']],cm:[['QUÈ ÉS?','Un estri fet d’un material que elimina marques de grafit'],['COM FUNCIONA?','que es frega sobre el paper per retirar el traç del llapis'],['PER A QUÈ SERVEIX?','i permet corregir o eliminar part del que s’ha escrit o dibuixat']],cs:[['QUÈ ÉS?','Un estri fabricat amb material flexible capaç d’arrossegar partícules de grafit'],['COM S’UTILITZA?','que actua per fregament sobre la superfície escrita'],['QUINA FUNCIÓ TÉ?','i permet eliminar o corregir traços fets principalment amb llapis']]},
    {word:'regla',area:'Escola',level:1,extra:'que pot ser transparent o de colors',ci:[['QUÈ ÉS?','Un estri recte amb marques de mesura'],['PER A QUÈ SERVEIX?','que serveix per mesurar i fer línies rectes']],cm:[['QUÈ ÉS?','Un instrument recte amb una escala de mesura marcada'],['QUÈ PERMET FER?','que permet calcular longituds petites'],['QUIN ALTRE ÚS TÉ?','i també serveix de guia per traçar línies rectes']],cs:[['QUÈ ÉS?','Un instrument allargat i recte que incorpora una escala graduada'],['QUINA FUNCIÓ DE MESURA TÉ?','que permet determinar longituds comparant-les amb les seves divisions'],['QUIN ALTRE ÚS TÉ?','i proporciona una vora recta per traçar segments i línies']]},
    {word:'tisores',area:'Escola',level:1,extra:'que poden tenir els mànecs de color blau',ci:[['QUÈ SÓN?','Un estri amb dues fulles que serveix per tallar'],['COM S’UTILITZEN?','que s’obren i es tanquen amb els dits']],cm:[['QUÈ SÓN?','Un instrument format per dues fulles unides per un eix'],['COM FUNCIONEN?','que les fulles s’apropen quan tanquem els mànecs'],['PER A QUÈ SERVEIXEN?','i permeten tallar paper, tela i altres materials']],cs:[['QUÈ SÓN?','Una eina de tall formada per dues fulles articulades'],['COM FUNCIONEN?','que les vores tallants es desplacen l’una contra l’altra en tancar els mànecs'],['QUINA FUNCIÓ TENEN?','i permeten seccionar materials relativament prims']]},
    {word:'pissarra',area:'Escola',level:1,extra:'que pot tenir imants o dibuixos enganxats',ci:[['QUÈ ÉS?','Una superfície gran on es pot escriure i esborrar'],['ON S’UTILITZA?','que es troba sovint a les classes']],cm:[['QUÈ ÉS?','Una superfície preparada per escriure-hi de manera temporal'],['COM S’UTILITZA?','que permet escriure i després esborrar el contingut'],['ON ÉS HABITUAL?','i s’utilitza sobretot en aules i espais de formació']],cs:[['QUÈ ÉS?','Una superfície de treball destinada a mostrar informació escrita o dibuixada temporalment'],['COM FUNCIONA?','que admet materials d’escriptura que després es poden eliminar'],['QUINA FUNCIÓ TÉ?','i facilita explicacions i activitats compartides davant d’un grup']]},
    {word:'carpeta',area:'Escola',level:1,extra:'que pot portar el nom d’una assignatura a la portada',ci:[['QUÈ ÉS?','Un objecte que serveix per guardar papers'],['PER A QUÈ SERVEIX?','que ajuda a tenir els fulls junts i ordenats']],cm:[['QUÈ ÉS?','Un objecte pla preparat per contenir documents'],['COM POT SER?','que pot tenir tapes, gomes, anelles o altres sistemes'],['PER A QUÈ SERVEIX?','i permet guardar i organitzar fulls']],cs:[['QUÈ ÉS?','Un element d’arxiu destinat a reunir i protegir documents'],['COM POT ORGANITZAR-SE?','que pot incorporar separadors, anelles o mecanismes de tancament'],['QUINA FUNCIÓ TÉ?','i facilita conservar, transportar i classificar papers']]},
    {word:'aula',area:'Escola',level:1,extra:'que pot tenir les parets decorades amb murals',ci:[['QUÈ ÉS?','Una sala on un grup d’alumnes fa classe'],['QUÈ S’HI FA?','que serveix per aprendre i treballar']],cm:[['QUÈ ÉS?','Un espai d’un centre educatiu destinat a fer classe'],['QUI L’UTILITZA?','que és utilitzat per alumnes i docents'],['QUÈ S’HI FA?','i permet realitzar activitats d’aprenentatge de manera individual o en grup']],cs:[['QUÈ ÉS?','Un espai físic d’un centre educatiu destinat principalment a l’ensenyament'],['QUI L’OCUPA?','que acull habitualment un grup d’alumnes i un o més docents'],['QUINA FUNCIÓ TÉ?','i proporciona les condicions necessàries per desenvolupar activitats d’aprenentatge']]},
    {word:'pati',area:'Escola',level:1,extra:'que pot tenir línies de colors pintades a terra',ci:[['QUÈ ÉS?','Un espai exterior de l’escola'],['QUÈ S’HI FA?','que s’utilitza sobretot per jugar i descansar']],cm:[['QUÈ ÉS?','Un espai obert que forma part habitualment d’una escola o edifici'],['COM S’UTILITZA A L’ESCOLA?','que permet sortir de l’aula durant els temps de descans'],['QUÈ S’HI FA?','i s’hi poden fer jocs, activitats o trobades']],cs:[['QUÈ ÉS?','Un espai descobert o parcialment descobert vinculat a un edifici'],['QUIN ÚS ESCOLAR TÉ?','que als centres educatius acull bona part del temps d’esbarjo'],['QUINES ACTIVITATS PERMET?','i facilita joc, descans, convivència i activitats a l’aire lliure']]},

    {word:'peu',area:'Cos humà',level:1,extra:'que pot portar un mitjó amb dibuixos',ci:[['QUÈ ÉS?','Una part del cos situada al final de la cama'],['PER A QUÈ SERVEIX?','que ens ajuda a estar drets i caminar']],cm:[['QUÈ ÉS?','La part del cos situada a l’extrem inferior de cada cama'],['COM ESTÀ FORMAT?','que inclou el taló, la planta i els dits'],['QUINA FUNCIÓ TÉ?','i participa en l’equilibri, el suport i el desplaçament']],cs:[['QUÈ ÉS?','La part terminal de l’extremitat inferior humana'],['COM ESTÀ ESTRUCTURAT?','que està formada per diversos ossos, articulacions i teixits'],['QUINA FUNCIÓ TÉ?','i suporta el pes corporal i intervé en l’equilibri i la locomoció']]},
    {word:'ull',area:'Cos humà',level:1,extra:'que pot quedar cobert per unes ulleres de sol',ci:[['QUÈ ÉS?','Una part del cos que ens permet veure'],['ON ÉS?','que es troba a la cara']],cm:[['QUÈ ÉS?','Un òrgan situat a la cara que capta la llum'],['QUÈ ENS PERMET?','que proporciona informació visual del que tenim al voltant'],['QUINA FUNCIÓ TÉ?','i és l’òrgan principal del sentit de la vista']],cs:[['QUÈ ÉS?','L’òrgan sensorial principal de la visió'],['COM FUNCIONA?','que rep la llum i la transforma en senyals que el sistema nerviós pot processar'],['QUINA FUNCIÓ TÉ?','i permet percebre formes, colors, moviments i distàncies']]},
    {word:'orella',area:'Cos humà',level:1,extra:'que pot portar una arracada',ci:[['QUÈ ÉS?','Una part del cos situada a cada costat del cap'],['PER A QUÈ SERVEIX?','que participa en el sentit de l’oïda']],cm:[['QUÈ ÉS?','La part externa visible de l’òrgan de l’oïda'],['QUÈ FA?','que ajuda a recollir els sons de l’entorn'],['ON ÉS?','i està situada a cada costat del cap']],cs:[['QUÈ ÉS?','La part externa de l’aparell auditiu situada als costats del cap'],['QUINA FUNCIÓ TÉ?','que recull ones sonores i les dirigeix cap a l’interior de l’oïda'],['AMB QUIN SENTIT ES RELACIONA?','i participa en el procés que permet percebre els sons']]},
    {word:'nas',area:'Cos humà',level:1,extra:'que pot quedar cobert parcialment per una bufanda',ci:[['QUÈ ÉS?','Una part de la cara situada entre els ulls i la boca'],['PER A QUÈ SERVEIX?','que ens permet respirar i olorar']],cm:[['QUÈ ÉS?','Una part de la cara que comunica amb les vies respiratòries'],['QUÈ ENS PERMET?','que deixa entrar i sortir aire i participa en l’olfacte'],['QUÈ CONTÉ?','i té dues obertures anomenades narius']],cs:[['QUÈ ÉS?','L’estructura externa situada al centre de la cara que forma l’entrada principal de les fosses nasals'],['QUINES FUNCIONS TÉ?','que participa en la respiració i en la percepció de les olors'],['COM ESTÀ OBERTA A L’EXTERIOR?','i presenta dues obertures anomenades narius']]},
    {word:'boca',area:'Cos humà',level:1,extra:'que pot estar pintada en un dibuix amb un color molt viu',ci:[['QUÈ ÉS?','Una obertura de la cara on hi ha les dents i la llengua'],['PER A QUÈ SERVEIX?','que utilitzem per menjar, parlar i respirar']],cm:[['QUÈ ÉS?','La cavitat de la cara que conté estructures com les dents i la llengua'],['QUÈ HI COMENÇA?','que és el lloc on comença la digestió dels aliments'],['QUINES ALTRES FUNCIONS TÉ?','i també participa en la parla i la respiració']],cs:[['QUÈ ÉS?','La cavitat situada a la part inferior de la cara que constitueix l’entrada del sistema digestiu'],['QUÈ CONTÉ?','que allotja estructures com les dents i la llengua'],['QUINES FUNCIONS TÉ?','i intervé en l’alimentació, l’articulació de la parla i, de manera complementària, la respiració']]},
    {word:'genoll',area:'Cos humà',level:2,extra:'que pot estar cobert per una genollera de color negre',ci:[['QUÈ ÉS?','La part de la cama que es doblega entre la cuixa i la part de baix'],['PER A QUÈ SERVEIX?','que ens permet doblegar i estirar la cama']],cm:[['QUÈ ÉS?','L’articulació que uneix la cuixa amb la part inferior de la cama'],['QUÈ PERMET?','que facilita principalment doblegar i estirar la cama'],['QUAN LA FEM SERVIR?','i intervé en accions com caminar, córrer o saltar']],cs:[['QUÈ ÉS?','L’articulació principal que connecta el fèmur amb els ossos de la part inferior de la cama'],['QUIN MOVIMENT PERMET?','que permet sobretot la flexió i l’extensió de la cama'],['QUINA FUNCIÓ TÉ?','i és essencial per sostenir el cos i realitzar nombrosos desplaçaments']]},
    {word:'cabell',area:'Cos humà',level:1,extra:'que es pot pentinar de moltes maneres diferents',ci:[['QUÈ ÉS?','El conjunt de pèls que creixen al cap'],['COM POT SER?','que pot tenir colors i formes diferents']],cm:[['QUÈ ÉS?','El conjunt de pèls que cobreixen bona part del cuir cabellut'],['COM POT VARIAR?','que pot ser llis, ondulat o arrissat i tenir colors diferents'],['QUINA FUNCIÓ TÉ?','i contribueix a protegir el cap i conservar una mica de calor']],cs:[['QUÈ ÉS?','El conjunt de filaments de queratina que creixen als fol·licles del cuir cabellut'],['COM POT VARIAR?','que presenta diferències de color, gruix i forma entre persones'],['QUINA FUNCIÓ TÉ?','i ofereix una certa protecció física i tèrmica al cap']]},

    {word:'parc',area:'Entorn',level:1,extra:'que pot tenir una font decorativa',ci:[['QUÈ ÉS?','Un espai a l’aire lliure amb zones per passejar o jugar'],['ON ÉS?','que sovint es troba dins d’un poble o una ciutat']],cm:[['QUÈ ÉS?','Un espai públic obert destinat al lleure i al contacte amb zones verdes'],['QUÈ POT TENIR?','que pot incloure arbres, camins, bancs o zones de joc'],['PER A QUÈ SERVEIX?','i permet passejar, descansar o fer activitats a l’aire lliure']],cs:[['QUÈ ÉS?','Un espai obert planificat per a usos recreatius, socials o ambientals'],['COM POT ESTAR ORGANITZAT?','que pot combinar vegetació, camins, mobiliari i zones d’activitat'],['QUINA FUNCIÓ TÉ?','i ofereix un lloc de lleure, descans i convivència dins o fora dels nuclis urbans']]},
    {word:'botiga',area:'Entorn',level:1,extra:'que pot tenir un aparador decorat per Nadal',ci:[['QUÈ ÉS?','Un lloc on es venen productes'],['QUÈ S’HI FA?','que les persones hi poden comprar coses']],cm:[['QUÈ ÉS?','Un establiment obert al públic on es venen productes'],['QUI HI PARTICIPA?','que hi treballen venedors i hi entren clients'],['QUÈ S’HI FA?','i s’hi compren i venen béns de diferents tipus']],cs:[['QUÈ ÉS?','Un establiment comercial destinat a la venda directa de productes al públic'],['COM FUNCIONA?','que ofereix uns béns a canvi d’un preu'],['QUINA FUNCIÓ TÉ?','i permet als consumidors adquirir productes de manera presencial']]},
    {word:'biblioteca',area:'Entorn',level:2,extra:'que pot tenir cartells de colors a l’entrada',ci:[['QUÈ ÉS?','Un lloc on hi ha molts llibres per llegir o agafar en préstec'],['PER A QUÈ SERVEIX?','que permet llegir, estudiar i buscar informació']],cm:[['QUÈ ÉS?','Un espai que conserva i posa a disposició llibres i altres documents'],['QUÈ HI PODEM FER?','que permet consultar materials, llegir o estudiar'],['QUIN SERVEI OFEREIX?','i sovint deixa emportar documents durant un temps mitjançant préstec']],cs:[['QUÈ ÉS?','Una institució o espai que organitza i posa a disposició una col·lecció de documents'],['QUINS SERVEIS OFEREIX?','que facilita la consulta, la lectura, l’estudi i l’accés a informació'],['QUÈ POT PERMETRE?','i habitualment ofereix préstec de llibres i altres recursos als usuaris']]},
    {word:'plaça',area:'Entorn',level:1,extra:'que pot tenir una escultura al centre',ci:[['QUÈ ÉS?','Un espai obert entre carrers i edificis'],['PER A QUÈ SERVEIX?','que permet passar, trobar-se o fer activitats']],cm:[['QUÈ ÉS?','Un espai públic obert situat dins d’un poble o una ciutat'],['COM ES CONNECTA?','que acostuma a comunicar-se amb diversos carrers'],['QUIN ÚS TÉ?','i serveix com a lloc de pas, trobada o activitat col·lectiva']],cs:[['QUÈ ÉS?','Un espai públic urbà obert, generalment delimitat per edificis o vies'],['COM S’INTEGRA A LA CIUTAT?','que connecta diferents recorreguts i pot concentrar serveis o equipaments'],['QUINA FUNCIÓ SOCIAL TÉ?','i actua sovint com a lloc de trobada, pas i celebració comunitària']]},
    {word:'platja',area:'Entorn',level:1,extra:'que pot tenir para-sols de molts colors',ci:[['QUÈ ÉS?','Una zona de sorra o pedres al costat del mar'],['QUÈ S’HI POT FER?','que permet caminar, jugar o banyar-se']],cm:[['QUÈ ÉS?','Una franja de costa coberta de sorra, grava o altres materials'],['ON ÉS?','que es troba al límit entre la terra i l’aigua'],['COM S’UTILITZA?','i sovint és un espai de bany, lleure i passeig']],cs:[['QUÈ ÉS?','Una acumulació de sediments situada a la vora d’una massa d’aigua'],['COM ES FORMA?','que és modelada contínuament per les onades, els corrents i el vent'],['QUIN ÚS HUMÀ TÉ?','i és utilitzada sovint per al lleure, el bany i altres activitats costaneres']]},
    {word:'muntanya',area:'Entorn',level:2,extra:'que pot aparèixer coberta de neu en una postal',ci:[['QUÈ ÉS?','Una gran elevació del terreny'],['COM ÉS?','que és més alta que les terres que l’envolten']],cm:[['QUÈ ÉS?','Una elevació natural important del terreny'],['COM ÉS?','que presenta pendents i una part superior més elevada'],['COM POT FORMAR-SE?','i es forma per processos geològics al llarg de molt de temps']],cs:[['QUÈ ÉS?','Una forma del relleu caracteritzada per una elevació considerable respecte del terreny proper'],['QUINES PARTS POT TENIR?','que presenta vessants i una zona superior o cim'],['COM S’ORIGINA?','i pot formar-se per moviments tectònics, activitat volcànica i altres processos geològics']]},
    {word:'bosc',area:'Entorn',level:2,extra:'que pot tenir un camí senyalitzat amb marques de pintura',ci:[['QUÈ ÉS?','Un lloc on creixen molts arbres i altres plantes'],['QUI HI POT VIURE?','que també és l’hàbitat de molts animals']],cm:[['QUÈ ÉS?','Un ecosistema terrestre on predominen els arbres'],['QUÈ HI TROBEM?','que també conté arbustos, herbes, fongs i molts animals'],['QUINA IMPORTÀNCIA TÉ?','i proporciona hàbitat i recursos a nombrosos éssers vius']],cs:[['QUÈ ÉS?','Un ecosistema terrestre dominat per una cobertura important d’arbres'],['QUINA DIVERSITAT TÉ?','que inclou moltes altres plantes, animals, fongs i microorganismes'],['QUINA FUNCIÓ ECOLÒGICA TÉ?','i intervé en la regulació del clima, del sòl, de l’aigua i de la biodiversitat']]},

    {word:'peix',area:'Animals',level:1,extra:'que pot viure en un aquari decorat amb pedres',ci:[['QUÈ ÉS?','Un animal que viu a l’aigua'],['COM ES MOU?','que neda amb aletes']],cm:[['QUÈ ÉS?','Un animal vertebrat adaptat a viure a l’aigua'],['COM RESPIRA?','que habitualment respira mitjançant brànquies'],['COM ES DESPLAÇA?','i es mou principalment utilitzant aletes']],cs:[['QUÈ ÉS?','Un vertebrat aquàtic que passa tota o gran part de la vida dins l’aigua'],['COM RESPIRA?','que en la majoria d’espècies obté oxigen mitjançant brànquies'],['COM ES DESPLAÇA?','i utilitza el cos i les aletes per controlar el moviment dins l’aigua']]},
    {word:'ocell',area:'Animals',level:1,extra:'que pot aparèixer dibuixat en una samarreta',ci:[['QUÈ ÉS?','Un animal amb plomes, bec i dues ales'],['COM ES MOU?','que moltes espècies poden volar']],cm:[['QUÈ ÉS?','Un animal vertebrat cobert de plomes i amb bec'],['COM ES REPRODUEIX?','que pon ous'],['COM ES DESPLAÇA?','i moltes espècies utilitzen les ales per volar']],cs:[['QUÈ ÉS?','Un vertebrat de sang calenta caracteritzat per tenir plomes i bec'],['COM ES REPRODUEIX?','que es reprodueix mitjançant ous amb closca'],['COM ES DESPLAÇA?','i la majoria d’espècies presenten ales adaptades al vol, encara que no totes volen']]},
    {word:'cavall',area:'Animals',level:1,extra:'que pot portar una manta de colors sobre el llom',ci:[['QUÈ ÉS?','Un animal mamífer gran amb quatre potes i crinera'],['COM ES RELACIONA AMB LES PERSONES?','que pot ser criat i muntat per les persones']],cm:[['QUÈ ÉS?','Un mamífer herbívor de mida gran amb quatre potes'],['COM ÉS?','que té peülles, crinera i una cua llarga'],['QUINA RELACIÓ TÉ AMB LES PERSONES?','i ha estat domesticat per al transport, el treball i activitats esportives']],cs:[['QUÈ ÉS?','Un mamífer herbívor domèstic de la família dels èquids'],['QUINES CARACTERÍSTIQUES TÉ?','que presenta potes acabades en peülles, crinera i gran capacitat de desplaçament'],['QUINA RELACIÓ TÉ AMB ELS HUMANS?','i ha estat utilitzat històricament per al transport, el treball i diverses activitats esportives']]},
    {word:'conill',area:'Animals',level:1,extra:'que pot viure en una caseta de fusta preparada per persones',ci:[['QUÈ ÉS?','Un animal mamífer petit amb orelles llargues'],['COM ES MOU?','que es desplaça fent salts']],cm:[['QUÈ ÉS?','Un mamífer herbívor de mida petita amb orelles llargues'],['COM ES MOU?','que té potes posteriors fortes adaptades al salt'],['ON POT VIURE?','i moltes espècies excaven caus al terra']],cs:[['QUÈ ÉS?','Un petit mamífer herbívor del grup dels lagomorfs'],['QUINES CARACTERÍSTIQUES TÉ?','que presenta orelles llargues i extremitats posteriors potents'],['COM VIU?','i diverses espècies construeixen o ocupen caus on es refugien']]},
    {word:'formiga',area:'Animals',level:1,extra:'que pot aparèixer en un dibuix portant una fulla',ci:[['QUÈ ÉS?','Un insecte petit amb sis potes'],['COM VIU?','que acostuma a viure amb moltes altres formigues']],cm:[['QUÈ ÉS?','Un insecte social de mida petita amb sis potes'],['COM S’ORGANITZA?','que viu en colònies formades per molts individus'],['ON VIU?','i construeix nius en llocs molt diversos']],cs:[['QUÈ ÉS?','Un insecte social de la família dels formícids'],['COM S’ORGANITZA?','que forma colònies amb individus que realitzen funcions diferents'],['ON POT VIURE?','i construeix nius al sòl, a la fusta o en altres espais protegits']]},
    {word:'papallona',area:'Animals',level:1,extra:'que pot tenir colors molt cridaners a les ales',ci:[['QUÈ ÉS?','Un insecte amb dues parelles d’ales'],['COM CANVIA?','que abans de ser adulta passa per l’etapa d’eruga']],cm:[['QUÈ ÉS?','Un insecte amb ales cobertes de petites escates'],['COM ES DESENVOLUPA?','que passa per una metamorfosi des de l’ou fins a l’adult'],['QUINA ETAPA ÉS MOLT CONEGUDA?','i durant una part del seu desenvolupament és una eruga']],cs:[['QUÈ ÉS?','Un insecte de l’ordre dels lepidòpters amb ales recobertes d’escates microscòpiques'],['COM ES DESENVOLUPA?','que experimenta una metamorfosi completa amb fases d’ou, larva, pupa i adult'],['COM ÉS LA LARVA?','i la fase larvària és coneguda habitualment com a eruga']]},

    {word:'caminar',area:'Accions',level:1,kind:'verb',extra:'que es pot fer portant una samarreta de qualsevol color',ci:[['QUÈ VOL DIR?','Desplaçar-se a peu'],['COM ES FA?','posant un peu davant de l’altre sense córrer']],cm:[['QUÈ VOL DIR?','Desplaçar-se d’un lloc a un altre utilitzant les cames'],['COM ES FA?','alternant els passos i mantenint normalment un peu en contacte amb el terra'],['PER A QUÈ HO FEM?','i permet moure’ns a una velocitat moderada']],cs:[['QUÈ VOL DIR?','Desplaçar el cos mitjançant una successió de passos'],['COM ES DIFERENCIA DE CÓRRER?','mantenint en condicions normals almenys un peu en contacte amb el terra'],['QUINA FUNCIÓ TÉ?','i constitueix una de les formes bàsiques de locomoció humana']]},
    {word:'saltar',area:'Accions',level:1,kind:'verb',extra:'que es pot fer escoltant música',ci:[['QUÈ VOL DIR?','Impulsar el cos per separar-lo del terra'],['COM ES FA?','fent força principalment amb les cames']],cm:[['QUÈ VOL DIR?','Elevar el cos mitjançant un impuls'],['COM ES FA?','fent força contra el terra amb una o dues cames'],['QUÈ PASSA?','i durant un moment el cos queda sense suport al terra']],cs:[['QUÈ VOL DIR?','Projectar el cos cap amunt, endavant o en una altra direcció mitjançant un impuls'],['COM ES PRODUEIX?','generant força contra una superfície, habitualment amb les extremitats inferiors'],['QUÈ EL CARACTERITZA?','i inclou una fase en què el cos queda temporalment sense contacte amb el suport']]},
    {word:'córrer',area:'Accions',level:1,kind:'verb',extra:'que es pot fer amb sabatilles de molts colors',ci:[['QUÈ VOL DIR?','Desplaçar-se ràpidament amb les cames'],['COM ES FA?','fent passos més ràpids que quan caminem']],cm:[['QUÈ VOL DIR?','Desplaçar-se a peu a una velocitat superior a caminar'],['COM ES FA?','alternant les cames amb impulsos ràpids'],['QUÈ EL DIFERENCIA DE CAMINAR?','i té moments en què cap peu toca el terra']],cs:[['QUÈ VOL DIR?','Desplaçar el cos mitjançant una successió ràpida de passes impulsades'],['QUÈ EL CARACTERITZA?','que presenta fases de vol en què els dos peus queden sense contacte amb el terra'],['QUINA FUNCIÓ TÉ?','i permet cobrir distàncies a peu amb més velocitat que caminant']]},
    {word:'mirar',area:'Accions',level:1,kind:'verb',extra:'que es pot fer mentre portem una gorra',ci:[['QUÈ VOL DIR?','Dirigir els ulls cap a alguna cosa'],['PER A QUÈ HO FEM?','per observar-la o veure-la millor']],cm:[['QUÈ VOL DIR?','Dirigir voluntàriament la vista cap a una persona, objecte o lloc'],['QUÈ IMPLICA?','que centrem l’atenció visual en allò que tenim davant'],['PER A QUÈ HO FEM?','i permet observar informació visual de manera intencionada']],cs:[['QUÈ VOL DIR?','Orientar intencionadament la mirada cap a un estímul visual'],['QUÈ IMPLICA?','que l’atenció es concentra en una zona, objecte o esdeveniment concret'],['QUINA FINALITAT POT TENIR?','i permet examinar, reconèixer o seguir visualment allò que observem']]},
    {word:'escoltar',area:'Accions',level:1,kind:'verb',extra:'que es pot fer assegut o dret',ci:[['QUÈ VOL DIR?','Parar atenció als sons que sentim'],['AMB QUIN SENTIT HO FEM?','utilitzant l’oïda']],cm:[['QUÈ VOL DIR?','Prestar atenció de manera intencionada als sons'],['AMB QUIN SENTIT ES FA?','que implica utilitzar el sentit de l’oïda'],['QUÈ PERMET?','i ajuda a comprendre veus, música o altres sons']],cs:[['QUÈ VOL DIR?','Atendre conscientment la informació que arriba a través del sentit de l’oïda'],['EN QUÈ ES DIFERENCIA DE SENTIR?','que implica una atenció intencionada i no només percebre un so'],['QUINA FUNCIÓ TÉ?','i permet interpretar missatges, música i altres estímuls sonors']]},
    {word:'menjar',area:'Accions',level:1,kind:'verb',extra:'que es pot fer en plats de colors diferents',ci:[['QUÈ VOL DIR?','Introduir aliments a la boca i empassar-los'],['PER A QUÈ HO FEM?','per alimentar-nos']],cm:[['QUÈ VOL DIR?','Consumir aliments introduint-los a la boca'],['QUÈ PASSA DESPRÉS?','que normalment els masteguem i els empassem'],['PER A QUÈ HO FEM?','i així el cos pot obtenir nutrients i energia']],cs:[['QUÈ VOL DIR?','Ingerir aliments perquè entrin al sistema digestiu'],['COM ES FA HABITUALMENT?','que implica introduir-los a la boca, mastegar-los quan cal i empassar-los'],['QUINA FUNCIÓ TÉ?','i permet incorporar al cos nutrients necessaris per al seu funcionament']]},
    {word:'beure',area:'Accions',level:1,kind:'verb',extra:'que es pot fer amb gots de formes diferents',ci:[['QUÈ VOL DIR?','Prendre un líquid per la boca i empassar-lo'],['PER A QUÈ HO FEM?','per incorporar líquids al cos']],cm:[['QUÈ VOL DIR?','Introduir un líquid a la boca i empassar-lo'],['QUÈ PERMET?','que fa arribar líquids al sistema digestiu'],['PER QUÈ ÉS IMPORTANT?','i contribueix a mantenir el cos hidratat']],cs:[['QUÈ VOL DIR?','Ingerir una substància líquida a través de la boca'],['QUÈ PASSA?','que el líquid és empassat i passa cap al sistema digestiu'],['QUINA FUNCIÓ TÉ?','i permet incorporar aigua o altres begudes necessàries o útils per a l’organisme']]},
    {word:'dormir',area:'Accions',level:1,kind:'verb',extra:'que es pot fer amb un pijama de dibuixos',ci:[['QUÈ VOL DIR?','Estar en un estat de descans en què tenim poca activitat conscient'],['PER A QUÈ SERVEIX?','permetent que el cos i el cervell descansin']],cm:[['QUÈ VOL DIR?','Passar un període en un estat natural de descans'],['QUÈ PASSA?','que disminueix la consciència del que passa al nostre voltant'],['PER QUÈ ÉS IMPORTANT?','i ajuda el cos i el cervell a recuperar-se']],cs:[['QUÈ VOL DIR?','Entrar en un estat biològic periòdic de repòs caracteritzat per una reducció de l’activitat conscient'],['QUÈ PASSA DURANT AQUEST ESTAT?','que disminueix la resposta voluntària als estímuls externs'],['QUINA FUNCIÓ TÉ?','i és essencial per a la recuperació física, la memòria i el funcionament del sistema nerviós']]}
  ];

  const cycles = {
    ci:{grades:[1,2],concept:1,boost:0},
    cm:{grades:[3,4],concept:1,boost:1},
    cs:{grades:[5,6],concept:1,boost:2}
  };

  function slug(value){
    return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'');
  }
  function hasOverlap(entry,grades){
    return Array.isArray(entry.grades) && entry.grades.some(g=>grades.includes(Number(g)));
  }
  function plausibleOptions(specIndex,cycle,segmentIndex,label){
    const correct=specs[specIndex][cycle][segmentIndex][1];
    const alternatives=[];
    for(let step=1;step<specs.length && alternatives.length<2;step++){
      const other=specs[(specIndex+step)%specs.length][cycle];
      if(!other) continue;
      let candidate=other.find(piece=>piece[0]===label);
      if(!candidate) candidate=other[Math.min(segmentIndex,other.length-1)];
      if(candidate && candidate[1]!==correct && !alternatives.includes(candidate[1])) alternatives.push(candidate[1]);
    }
    return [correct,...alternatives];
  }

  for(const [cycle,cfg] of Object.entries(cycles)){
    specs.forEach((spec,specIndex)=>{
      if(data.some(entry=>entry.word===spec.word && hasOverlap(entry,cfg.grades))) return;
      const pieces=spec[cycle];
      if(!pieces) return;
      data.push({
        id:`${cycle}-every-${slug(spec.word)}`,
        word:spec.word,
        grades:cfg.grades,
        area:spec.area,
        kind:spec.kind||'nom',
        conceptDifficulty:cfg.concept,
        definitionDifficulty:Math.max(1,Math.min(5,(spec.level||1)+cfg.boost)),
        vocab:'quotidia',
        segments:pieces.map((piece,segmentIndex)=>({
          label:piece[0],
          correct:piece[1],
          options:plausibleOptions(specIndex,cycle,segmentIndex,piece[0])
        })),
        extra:spec.extra
      });
    });
  }
})();